version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
      timezone: Asia/Tokyo
    groups:
      production:
        dependency-type: production
        update-types:
          - patch
          - minor
        # patternよりもdependency typeが先にマッチしてしまうので、react-routerはpatternに含まれるようここでは除外
        exclude-patterns:
          - "@react-router/*"
          - "react-router"
      development:
        dependency-type: development
        update-types:
          - patch
          - minor
        # patternよりもdependency typeが先にマッチしてしまうので、react-routerはpatternに含まれるようここでは除外
        exclude-patterns:
          - "@react-router/*"
          - "react-router"
      react-router:
        patterns:
          - "@react-router/*"
          - "react-router"
      
